# Generated by Django 4.2.5 on 2023-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='hi', upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
